### PR TITLE
feat: prettier pallet move rpc results, get-module-abi

### PR DESCRIPTION
**Pull request by neutrinoks**
RPC method `get_module_abi` now returns the original `ModuleAbi` defined in `move-vm-backend-common` instead of `Vec<u8>`

### CODE REVIEW

**Review by asmie — CHANGES_REQUESTED** [review]
Let's re-run the GH actions once `substrate-move` PR will be merged to check if tests pass.
Overall LGTM :+1:

**Review by Rqnsom — DISMISSED** [review]
LGTM :ok_hand:

**Review by Rqnsom — APPROVED** [review]
Let's goooo

**Review by asmie — APPROVED** [review]
👍

**Pull request merged**
